DA/urls.py
from django.urls import path

from . import views

app_name = 'DA'

urlpatterns=[
    #Home Page
    path('', views.index, name='index'),

    #View all Entries
    path('entries/', views.entries, name='entries'),

    #New entry(data)
    path('new_data/<int:entry_id>', views.add_data, name='new_data'),

    #View data
    path('data/', views.view_all_data, name='data'),

    #Individual Entry
    path('entries/<int:entry_id>/', views.entry,name="entry"),

    #New Topic
    path('new_entry/', views.new_entry, name="new_entry"),

    #Edit Entry
    path('edit_data/<int:data_id>', views.edit_data, name='edit_data'),

    #Delete data
    path('delete_data/<int:data_id>', views.delete_data, name='delete_data'),

    #View unique post data
    path('entries/<int:entry_id>/data', views.view_some_data, name="entry_data"),

    #View graphs??? One for now
    path('entries/<int:entry_id>/graph', views.graph, name="graph"),
]

IA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('DA.urls', namespace='DA')),
    path('users/',include('Users.urls', namespace='Users')),
]

Users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views

app_name = "users"

urlpatterns = [
    #Login
    path('login/', LoginView.as_view(template_name='Users/login.html'), name='login'),
    #Logout
    path('logout/', LogoutView.as_view(template_name='Users/logout.html'), name='logout'),
    #Register
    path('register/', views.register, name='register'),
]

DA/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, timedelta
# Create your models here.


class IntegerRangeField(models.IntegerField):
    def __init__(self, verbose_name=None, name=None, min_value=None, max_value=None, **kwargs):
        self.min_value, self.max_value = min_value, max_value
        models.IntegerField.__init__(self, verbose_name, name, **kwargs)
    def formfield(self, **kwargs):
        defaults = {'min_value':self.min_value, 'max_value':self.max_value}
        defaults.update(**kwargs)
        return super(IntegerRangeField, self).formfield(**defaults)


def default_start_time():
    now = datetime.now()
    start = now.replace(hour=22, minute=0, second=0, microsecond=0)
    return start if start > now else start + timedelta(days=1)

class Entry(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

class Info(models.Model):
    entry = models.ForeignKey(Entry, on_delete=models.DO_NOTHING)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    start = models.TimeField(blank=True, default=default_start_time)
    end = models.TimeField(blank=True, default=default_start_time)
    day = IntegerRangeField(min_value=0, max_value=31)
    month = IntegerRangeField(min_value=0,max_value=12)
    year = models.IntegerField()
    
    class Meta:
        verbose_name_plural = 'data'

    def __str__(self):
        return self.text

DA/forms.py
from django import forms

from . models import Info, Entry
import datetime

class InfoForm(forms.ModelForm):
    start = forms.TimeField(widget=forms.TimeInput(format='%H:%M'))
    end = forms.TimeField(widget=forms.TimeInput(format='%H:%M'))
    class Meta:
        model = Info
        fields = ['text', 'month','day', 'year','start', 'end']
        labels = {'text':'Thoughts on the event', 'month':'Enter month','day':'Enter in day','year':'Enter year','start':'Starting time(in military time)', 'end':'Ending time(in military time)'}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}


Day_Choices = [
    ('day','Day'),
    ('week','Week'),
    ('year','Year'),
    ('all','All'),
]
class DataForm(forms.Form):
    days_view = forms.CharField(label='How many days of data to view?', widget=forms.Select(choices=Day_Choices))

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}   

Delete_Choices = [
    ('yes','yes'),
    ('no','no')
]
class DeleteForm(forms.Form):
    del_choice = forms.ChoiceField(choices=Delete_Choices, widget=forms.RadioSelect)

yd = []
for y in range(1990,(datetime.datetime.now().year + 5)):
    yd.append((y,y))
class YearForm(forms.Form):
    year = forms.ChoiceField(label='What year do you want to see data for?', choices=yd)

DA/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect , Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

#from .models import Topic, Entry
#from .forms import TopicForm, EntryForm
from .models import Info, Entry
from .forms import InfoForm, DataForm , EntryForm, DeleteForm, YearForm
from .datav import graph

from datetime import datetime, timedelta
from .helper import checker, grapher, scatter_year_amount, scatter_month_amount, scatter_month_amount_color, hour_per_month
import plotly

# Create your views here.

def check_data_owner(request, data):
    return request.user == data.owner


def get_time_diff(start, end):
    starter = 60*start.hour + start.minute
    ender = 60*end.hour + end.minute
    return ender - starter

def index(request):
    return render(request, 'DA/index.html')

# view all entries(regardless of main val)
@login_required
def entries(request):
    entries = Entry.objects.filter(owner=request.user).order_by('date_added')
    print(request.user)
    context = {'entries':entries}
    return render(request, 'DA/entries.html', context)

# View entry
@login_required
def entry(request, entry_id):
    entry = get_object_or_404(Entry, id=entry_id)
    if not check_data_owner(request, entry):
        raise Http404
    data = entry.info_set.order_by('-date_added')
    times = []
    for c in entry.info_set.all():
        times.append(get_time_diff(c.start, c.end))
    context = {'entry': entry, 'data': data, 'times':times}
    return render(request, 'DA/entry.html', context)

# add a data point
@login_required
def add_data(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    if request.method != 'POST':
        form = InfoForm()
    else:
        #POST request submitted
        form = InfoForm(data=request.POST)
        if form.is_valid() and request.user == entry.owner:
            new_entry = form.save(commit=False)
            new_entry.entry = entry
            new_entry.save()
            print(request.POST['start'])
            return HttpResponseRedirect(reverse('DA:entry', args=[entry_id]))
    context = {'entry':entry,'form':form}
    return render(request, 'DA/new_data.html', context)

# add entry(main topic)
@login_required
def new_entry(request):
    if request.method != 'POST':
        form = EntryForm()
    else:
        #there is some data
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('DA:entries'))
    context = {'form': form}
    return render(request, 'DA/new_entry.html', context)

# Edit data point
@login_required
def edit_data(request, data_id):
    """edit entry"""
    data = Info.objects.get(id=data_id)
    entry = data.entry

    if request.method != 'POST':
        form = InfoForm(instance=data)
    else:
        form = InfoForm(instance=data, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('DA:entry', args=[entry.id]))
    context = {'data': data, 'entry': entry, 'form':form}
    return render(request, 'DA/edit_data.html', context)

# View data from past days
@login_required
def view_all_data(request):
    bob = ""
    if request.method!='POST':
        form = DataForm()
    else:
        form = DataForm(data=request.POST)
        if form.is_valid():
            days = []
            d = form.cleaned_data['days_view']
            bob = d
            elements = Info.objects.all().order_by('-date_added')
            for c in elements:
                if(c.entry.owner == request.user):
                    days.append((c.day, c.month, c.year, c.start, c.end, c.text, c.date_added, c.entry))

                #b = c.entry.owner
                #entries = Info.objects.filter(b=request.user)
                #for e in entries:
                #    days[e.day] = e.month
            print(d)
    context = {'form':form}
    if(len(bob)):
        if(bob =="day"):
            context['days'] = checker(days, 1.1)
        elif(bob =="year"):
            context['days'] = checker(days, 365)
        elif(bob=="week"):
            context['days'] = checker(days, 7)
        elif(bob=="all"):
            context['days'] = days
        else:
            context['days'] = []
    return render(request, 'DA/data.html', context)


@login_required
def delete_data(request, data_id):
    data = Info.objects.get(id=data_id)
    if request.method != 'POST':
        form = DeleteForm()
    else:
        #there is some data
        form = DeleteForm(data=request.POST)
        if form.is_valid():
            d = form.cleaned_data['del_choice']
            if(d == 'yes'):
                Info.objects.filter(id=data_id).delete()
            else:
                pass
            return HttpResponseRedirect(reverse('DA:entries'))
    context = {'data':data,'form': form}
    return render(request, 'DA/delete_data.html', context)

@login_required
def view_some_data(request, entry_id):
    bob = ""
    if request.method!='POST':
        form = DataForm()
    else:
        form = DataForm(data=request.POST)
        if form.is_valid():
            days = []
            d = form.cleaned_data['days_view']
            bob = d
            entry = Entry.objects.get(id=entry_id)
            data = entry.info_set.order_by('-date_added')
            for c in data:
                if(c.entry.owner == request.user):
                    days.append((c.day, c.month, c.year, c.start, c.end, c.text, c.date_added))

                #b = c.entry.owner
                #entries = Info.objects.filter(b=request.user)
                #for e in entries:
                #    days[e.day] = e.month
            print(d)
    context = {'form':form, 'e_id':entry_id}
    if(len(bob)):
        if(bob =="day"):
            context['days'] = checker(days, 1)
        elif(bob =="year"):
            context['days'] = checker(days, 365)
        elif(bob=="week"):
            context['days'] = checker(days, 7)
        elif(bob=="all"):
            context['days'] = days
        else:
            context['days'] = []
    return render(request, 'DA/entry_data.html', context)

@login_required
def graph(request, entry_id):
    bob = ""
    year = 2023
    if request.method != 'POST':
        form = YearForm()
    else:
        form = YearForm(data=request.POST)
        if form.is_valid():
            year = form.cleaned_data['year']
            print(year)

    graph_div = plotly.offline.plot(grapher(), auto_open=False, output_type="div")
    entry = Entry.objects.get(id=entry_id)
    data = entry.info_set.order_by('-date_added')
    day_list, month_list, year_list, da = [] , [] , [] , []
    hour = [0 for _ in range(12)]
    sessions = [0 for _ in range(12)]
    for c in data:
        if(c.entry.owner == request.user):
            year_list.append(c.year)
            if(c.year == int(year)):
                day_list.append(c.day)
                month_list.append(c.month)
                start = 60 * c.start.hour + c.start.minute
                end = 60 * c.end.hour + c.end.minute
                hour[c.month] += int(end - start)
                sessions[c.month] += 1
            print(hour)
            da.append(c.date_added)
    year_graph_scatter = scatter_year_amount(year_list)
    scatter_ma= scatter_month_amount(month_list, day_list)
    #scatter_mac = scatter_month_amount_color(month_list,day_list)
    bar_hour = hour_per_month(month_list, hour, sessions)
    context = {'eid':entry_id,'graph':year_graph_scatter,'graph2':scatter_ma, 'graph3':bar_hour, 'form':form}
    return render(request, 'DA/graph.html', context)

def new_entry(request):
    if request.method != 'POST':
        form = EntryForm()
    else:
        #there is some data
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('DA:entries'))
    context = {'form': form}
    return render(request, 'DA/new_entry.html', context)

DA/templates/DA/base.html
{% load bootstrap3 %} 
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Planner</title>

        {% bootstrap_css %} 
        {% bootstrap_javascript %} 
    </head>
    <body>
        <!--Static navbar-->
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    </button>
                    <a class="navbar-brand" href="{% url 'DA:index' %}">Home</a>
                </div>

                <div id="navbar" class="navbar-collapse collapse">
                    <ul class=" nav navbar-nav">
                        <li><a href="{% url 'DA:entries' %}">Activities</a></li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'DA:data' %}">All Data</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %} 
                            <li><a>Hello, {{ user.username }} </a></li>
                            <li><a href="{% url 'Users:logout' %}">Log Out</a></li>
                        {% else %} 
                            <li><a href="{% url 'Users:register' %}">Register</a></li>
                            <li><a href= "{% url 'Users:login' %}">Log In</a></li>
                        {% endif %}
                    </ul>
                </div><!--/.nav-collapse-->
            </div><!-- /container-->
        </nav>
        <div class="container">
            <div class="page-header">
                {% block header %}{% endblock header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>
        </div><!-- /container -->
    </body>
</html>

DA/templates/DA/data.html
{% extends "DA/base.html" %}
{% load bootstrap3 %} 

{% block header %}
    <h2>View Data</h2>
{% endblock header %}

{% block content %} 
    <form action="{% url 'DA:data' %}" method='post' class="form">
        {% csrf_token %} 
        {% bootstrap_form form %}

        {% buttons %} 
            <button name="submit" class="btn btn-primary">View Data</button>
        {% endbuttons %}      
    </form>
    {% for d,m,y,s,e,t,da,entry in days %} 
        <div class="panel panel-default"> 
            <div class="panel-heading">
                <h3>
                    <strong>{{ m }}</strong> - <strong>{{ d }}</strong> - <strong>{{ y }}</strong>
                    <strong>|</strong>
                    <strong>{{ s }}</strong> - <strong>{{ e }}</strong>
                </h3>
            </div>
            <div class="panel-body">
                <strong>Thoughts:</strong>{{ t|linebreaks }}
            </div>
            <div class="panel-body">
                <small><strong>Actual date added: </strong>{{ da|date:'M d, Y H:i' }}</small>
                <small><strong>Entry: </strong>{{ entry }}</small>
            </div>
        </div><!-- panel -->
    {% empty %}
        No entries match your request.
    {% endfor %}
    
{% endblock content %}

DA/templates/DA/delete_data.html
{% extends "DA/base.html" %} 
{% load bootstrap3 %} 

{% block content %} 
    
    <p>Do you wish to delete this datapoint? </p>
    <form action="{% url 'DA:delete_data' data.id %}" method='post'>
        {% csrf_token %} 
        {{ form.as_p }}
        {% buttons %} 
            <button name="submit" class="btn btn-primary">Delete Entry</button>
        {% endbuttons %}   
    </form>
{% endblock content %}

DA/templates/DA/edit_data.html
{% extends "DA/base.html" %} 
{% load bootstrap3 %} 
{% block header %} 
    <p><a href="{% url 'DA:entry' entry.id %}">{{ entry }}</a></p>
{% endblock header %}
{% block content %} 

    <p>Edit entry: </p>
    <form action="{% url 'DA:edit_data' data.id%}" method='post'>
        {% csrf_token %} 
        {% bootstrap_form form %}

        {% buttons %} 
            <button name="submit" class="btn btn-primary">Edit entry</button>
        {% endbuttons %} 
    </form>
{% endblock content %}

DA/templates/DA/entries.html
{% extends 'DA/base.html' %} 

{% block header %} 
    <h1>Activities</h1>
{% endblock header %}

{% block content %} 
    <p>Activities</p>
    <ul>
        {% for entry in entries %} 
            <li>
                <h3>
                    <p style="text-align: left;">{{ entry }} - {{ entry.date_added|date:'M d, Y H:i' }}
                        <span style="float:right;">
                            <a class="float-right" href="{% url 'DA:entry' entry.id %}">{{ entry }}</a>
                        </span>
                    </p>
                </h3>
            </li>
        {% empty %} 
            <li>No entries have been recorded</li>
        {% endfor %}
    </ul>

    <span></span>
    <h3><a href="{% url 'DA:new_entry' %}">Add activity</a></h3>
{% endblock content %}

DA/templates/DA/entry.html
{% extends "DA/base.html" %}

{% block header %} 
    <div style="display:flex;justify-content:space-between">
        <h1 style="display:inline-block;">{{ entry }}</h1>
        <h1 class="text-right" style="display:inline-block "><a href= "{% url 'DA:entries' %}">Back</a></h1>
    </div>
    <div style="display:flex;justify-content: space-between;">
        <h1 style="display:inline-block;font-size:medium"><a href="{% url 'DA:entry_data' entry.id %}">View Specific Data</a></h1>
        <h1 style="display:inline-block;font-size:medium"><a href="{% url 'DA:graph' entry.id %}">View Graphs</a></h1>
    </div>
{% endblock header %}
{% block content %}

    <p>Entries:</p>
    <p><a href="{% url 'DA:new_data' entry.id %}">Add a new entry</a></p>

    {% for d in data %}
        <div class="panel panel-default"> 
            <div class="panel-heading">
                <h3>
                    <strong>{{ d.month }}</strong> - <strong>{{ d.day }}</strong> - <strong>{{ d.year }}</strong>
                    <strong>|</strong>
                    <strong>{{d.start}}</strong> - <strong>{{ d.end }}</strong>
                    <strong>|</strong>
                    <!-- <strong></strong>
                    <strong>|</strong> -->
                    <small >
                        <a href="{% url 'DA:edit_data' d.id %}">Edit Entry</a>
                    </small>
                    <strong>|</strong>
                    <small >
                        <a href="{% url 'DA:delete_data' d.id %}">Delete Entry</a>
                    </small>
                </h3>
            </div>
            <div class="panel-body">
                <strong>Thoughts:</strong>{{ d.text|linebreaks }}
            </div>
            <div class="panel-body">
                <small><strong>Actual date added: </strong>{{ d.date_added|date:'M d, Y H:i' }}</small>
            </div>
        </div><!-- panel -->
    {% empty %}
        There are no entries yet.
    {% endfor %}
{% endblock content %}

DA/templates/DA/entry_data.html
{% extends "DA/base.html" %}
{% load bootstrap3 %} 

{% block header %}
    <div style="display:flex;justify-content:space-between">
        <h1 style="display:inline-block;">View Data</h1>
        <h1 class="text-right" style="display:inline-block "><a href= "{% url 'DA:entries' %}">Back</a></h1>
    </div>
{% endblock header %}

{% block content %} 
    <form action="{% url 'DA:entry_data' e_id %}" method='post' class="form">
        {% csrf_token %} 
        {% bootstrap_form form %}

        {% buttons %} 
            <button name="submit" class="btn btn-primary">View Data</button>
        {% endbuttons %}      
    </form>
    {% for d,m,y,s,e,t,da in days %} 
        <div class="panel panel-default"> 
            <div class="panel-heading">
                <h3>
                    <strong>{{ m }}</strong> - <strong>{{ d }}</strong> - <strong>{{ y }}</strong>
                    <strong>|</strong>
                    <strong>{{ s }}</strong> - <strong>{{ e }}</strong>
                </h3>
            </div>
            <div class="panel-body">
                <strong>Thoughts:</strong>{{ t|linebreaks }}
            </div>
            <div class="panel-body">
                <small><strong>Actual date added: </strong>{{ da|date:'M d, Y H:i' }}</small>
            </div>
        </div><!-- panel -->
    {% empty %}
        No entries match your request.
    {% endfor %}
    
{% endblock content %}

DA/templates/DA/graph.html
{% extends "DA/base.html" %}
{% load bootstrap3 %} 

{% block header %}
<div style="display:flex;justify-content:space-between">
    <h1 style="display:inline-block;">View Graphs</h1>
    <h1 class="text-right" style="display:inline-block "><a href= "{% url 'DA:entries' %}">Back</a></h1>
</div>
{% endblock header %}

{% block content %}
    <h1 style="text-align:center;">Amount of Entries per year</h1>
    <div style="width:1000;height:100">
        {{ graph|safe }}
    </div>
        <h1 style="text-align: center;">Amount of entries per month</h1>
        <form action="{% url 'DA:graph' eid %}" method='post' class="form">
            {% csrf_token %} 
            {% bootstrap_form form %}
    
            {% buttons %} 
                <button name="submit" class="btn btn-primary">Enter Year</button>
            {% endbuttons %}      
        </form>
    {% if graph2 %}
        <div style="width:1000;height:100">
            {{ graph2|safe }}
        </div>
        <div style="width:1000;height:100">
            {{ graph3|safe }}
        </div>
    {% else %} 
        <p style="text-align: center;">There is no data for this year.</p>
    {% endif %}
{% endblock content %}

DA/templates/DA/index.html
{% extends "DA/base.html" %}
{% block header %} 
    <div class='jumbotron'>
        <h1>IA Project 2023</h1>
    </div>
{% endblock header %}
{% block content %}
    <p>Log activities and sessions</p>

    <p>View data as you please.</p>

    <!--<p>Very op, would recommend 10/10</p> -->

    <h2>
        <a href="{% url 'users:register' %}">Register</a>
        an account.
    </h2>
    <h2>
        <a href="{% url 'DA:entries' %}">Create</a>
        activities and enter sessions.

    </h2>
{% endblock content %}

DA/templates/DA/new_data.html
{% extends "DA/base.html" %}
{% load bootstrap3 %} 

{% block header %}
    <h2>Add Data:</h2>
{% endblock header %}

{% block content %} 
    <p><a href="{% url 'DA:entry' entry.id %}">{{ entry }}</a></p>    
    <form action="{% url 'DA:new_data' entry.id %}" method='post' class="form">
        {% csrf_token %} 
        {% bootstrap_form form %}

        {% buttons %} 
            <button name="submit" class="btn btn-primary">add entry</button>
        {% endbuttons %}      
    </form>
{% endblock content %}

DA/templates/DA/new_entry.html
{% extends "DA/base.html" %}
{% load bootstrap3 %} 

{% block header %}
    <h2>Add entry:</h2>
{% endblock header %}

{% block content %} 
    <form action="{% url 'DA:new_entry' %}" method='post' class="form">
        {% csrf_token %} 
        {% bootstrap_form form %}

        {% buttons %} 
            <button name="submit" class="btn btn-primary">add topic</button>
        {% endbuttons %}      
    </form>
{% endblock content %}